#!/usr/bin/env bash
# Displays a story with each line of /etc/passwd

INPUT_FILE="/etc/passwd"
while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIRECTORY SHELL
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"
done < "$INPUT_FILE"

