#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration, displays Best School and then Hi

ITERATION=0
while [ $ITERATION -lt 11 ]
do
	if [ $ITERATION -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	ITERATION=$(( ITERATION + 1 ))
done

