#!/usr/bin/env bash
# This script displays the content of the current directory in a list format where only the part of the name after the first dash is displayed

for file_name in *
do
	echo "$file_name" | cut -d'-' -f2
done

