#!/usr/bin/env bash
# Displays information about the holbertonschool file

FILE_NAME="school"

if [ -e "$FILE_NAME" ]
then
	echo "$FILE_NAME file exists"
	if [ ! -s "$FILE_NAME" ]
	then
		echo "$FILE_NAME file is empty"
	else
		echo "$FILE_NAME file is not empty"
	fi
	if [ -f "$FILE_NAME" ]
	then
		echo "$FILE_NAME is a regular file"
	fi
else
	echo "$FILE_NAME file does not exist"
fi

